### ISSUE TITLE
YoCode doesn't kill processes if it times out

### ISSUE THREAD

**Issue by SerCoach1** [FairlyLinearDynamics/YoCode#93]
When comparing applicant's code, if a timeout occurs, applicant's project is left running

**Comment by SerCoach1** [comment]
Steps to reproduce:
1. make YoCode timeout, e.g. in ProjectRunner line 33 change 
`var evidence = featureRunner.Execute(processDetails, "Application started. Press Ctrl+C to shut down.", false);` to
`var evidence = featureRunner.Execute(processDetails);`
2. Run automated tests, specifically CompareProjects tests.

**Comment by jogobom** [comment]
I've had a chance to look at this now and it the problem is, as you originally said, we're unable to kill child processes correctly when something goes wrong. It's been identified as something missing in .Net Core: https://github.com/dotnet/corefx/issues/26234

One option might be to make our AutomatedTests project a .Net Framework project rather than .Net Core. That would enable us to use WMI to find all the child processes and kill them.
